Criação do projeto
gms1227/profile-back pull request #1
Opened 2023-03-30 13:19 UTC by gms1227

2023-03-30 13:46 UTC, julianostroschon requested changes
alguns comentários

2023-03-30 13:46 UTC, julianostroschon commented on .gitignore
> +.gitignore
como acontecerá o gitignore se este arquivo não for para o repositório?

2023-03-30 13:46 UTC, julianostroschon commented on src/graphql/context/index.js
> +const knex = require('../../database/index.js');
o comportamento padrão é referenciar somente a pasta, o JavaScript já entenderá que tu estás acionando a index daquela pasta. Portanto, desnecessário referenciar o index de uma pasta.

2023-03-30 13:46 UTC, julianostroschon commented on src/graphql/resolvers/graphql.js
> +const { users } = require('./query/');
`graphql.js`?

2023-03-30 13:46 UTC, julianostroschon commented on src/graphql/resolvers/mutation/index.js
> +};
Sempre que a chave e o valor de um objeto tem o mesmo nome, não se faz necessária a repetição...
❌
```
{
 id: id
}
```
✅
```
{ 
 id 
} 
```

2023-04-14 17:28 UTC, merged

2023-04-17 12:54 UTC, julianostroschon commented on src/database/migrations/20230406141631_users.js
> +        'https://imgs.search.brave.com/IAtJtSNSIVSRMro9vXSxnc2FpSrB-ZeOLbZY9nhKJDc/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly9ib29r/aW5nLnNpL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDE4LzEyL2Rl/ZmF1bHRfYXZhdGFy/LTIwNDh
poderia baixar essa imagem para o teu front, e acessar-lá quando não houvesse imagem cadastrada, isso reduziria o acesso a serviços externos em cada execução, bem como diminuiria o consumo de dados

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/context/index.js
> +    bcrypt,
toda a aplicação terá acesso a `bcrypt` pq?

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/field/languages.js
> +  return parent;
isso funciona?

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/mutation/auth.js
> +      'description',
boa, não conhecia essa forma de selecionar os dados

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/mutation/auth.js
> +      'password',
mas tu tá mandando a senha junto?

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/mutation/edit.js
> +    .returning('password')
pq retornar a senha?

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/mutation/languages.js
> +  return true;
sempre retornará `true`

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/mutation/languages.js
> +    js: languages.find((langId) => langId == 1),
melhorar essa solução, tá ruim

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/mutation/register.js
> +  let verify = await knex('users').first('email').where({
não usar `let`

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/mutation/register.js
> +  let verify = await knex('users').first('email').where({
condição estranha

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/query/languagesUser.js
> +  if (languages == '') {
errado

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/query/searchUser.js
> +  if (searchUsers == '') {
errado

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/query/searchUser.js
> +  searchUsers.sort(function (a, b) {
pq?

2023-04-17 12:54 UTC, julianostroschon commented on src/graphql/resolvers/query/users.js
> +  usersList.sort(function (a, b) {
pq sort?

2023-04-17 13:09 UTC, gms1227 commented on src/graphql/resolvers/query/users.js
> +  usersList.sort(function (a, b) {
para mandar os usuarios ordenados por id para o front

2023-04-17 13:22 UTC, gms1227 commented on src/graphql/resolvers/field/languages.js
> +  return parent;
sim, fiz de acordo com a documentação